# Generated by Django 3.2.13 on 2022-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('user', models.CharField(max_length=32)),
                ('tool', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
